import type { ExecutableCaseDefinition } from "../types";
import { confirmedThreshold, controlledUncertainty, manualDecisionInputs, syntheticPriorDecision } from "../types";

export const FINANCIAL_RISK_CASE: ExecutableCaseDefinition = {
  id: "financial-risk", title: "Financial Risk: Portfolio Risk and Admission Thresholds", projectName: "Synthetic Credit-Portfolio Decision Audit", primaryKey: "account_id",
  baselineFile: "/cases/financial-risk/baseline.csv", currentFile: "/cases/financial-risk/current.csv", expectedGeneratedAt: "2026-08-08T00:00:00.000Z",
  claims: [
    { id: "finance-pd-gate", code: "FR-001", title: "Mean portfolio probability of default does not exceed 4%", section: "Risk admission", owner: "Risk owner", category: "Risk threshold", formula: "mean(pd_percent) <= 4", rule: { type: "threshold", field: "pd_percent", aggregation: "average", operator: "<=", threshold: 4, thresholdSpec: confirmedThreshold(4, "percent", "Synthetic credit policy v1", "Pause expansion when mean PD exceeds 4%") } },
    { id: "finance-pd-stability", code: "FR-002", title: "Mean portfolio probability of default changes by no more than 5%", section: "Model monitoring", owner: "Model risk owner", category: "Risk stability", formula: "relative_change(mean(pd_percent)) <= 5%", rule: { type: "stability", field: "pd_percent", aggregation: "average", supportTolerance: 5, reversalThreshold: 15, supportToleranceSpec: confirmedThreshold(5, "percent", "Synthetic model monitoring policy v1", "Treat changes within 5% as stable for monitoring"), reversalThresholdSpec: confirmedThreshold(15, "percent", "Synthetic risk escalation policy v1", "A 15% change invalidates the original portfolio assumption") } },
    { id: "finance-label-gate", code: "FR-003", title: "The observed default-label share does not exceed 25%", section: "Post-hoc validation", owner: "Validation owner", category: "Outcome threshold", formula: "mean(observed_label) <= 0.25", rule: { type: "threshold", field: "observed_label", aggregation: "average", operator: "<=", threshold: 0.25, thresholdSpec: confirmedThreshold(0.25, "score", "Synthetic validation policy v1", "Stop the original admission policy when the observed default rate exceeds 25%") } },
  ],
  decisions: [{ id: "finance-underwriting", title: "Should admission expand under the original policy?", owner: "Credit committee", passActionId: "finance:continue-admission", holdActionId: "finance:pause-and-reestimate", actionIfPass: "Continue admission within the risk budget.", actionIfFail: "Pause expansion and re-estimate portfolio thresholds.", conditions: [{ claimId: "finance-pd-gate", allowedStatuses: ["SUPPORTED"] }, { claimId: "finance-label-gate", allowedStatuses: ["SUPPORTED"] }], priorSignedResult: syntheticPriorDecision({ decisionId: "finance-underwriting", versionId: "finance-v1", outcome: "PASS", activeActionId: "finance:continue-admission", activeActionInstruction: "Continue admission within the risk budget.", recommendedOptionId: "expand", feasibleOptionIds: ["pause", "tighten", "expand"], claimIds: ["finance-pd-gate", "finance-label-gate"], signedAt: "2026-08-01T08:00:00.000Z", signedBy: "Synthetic credit committee" }), stakeholders: ["Credit committee", "Customers", "Capital management"], objective: { benefitWeight: 1, costWeight: 0.15, riskWeight: 1.5 }, riskTolerance: 20, noActionLoss: 28, inputProvenance: manualDecisionInputs("Synthetic credit committee assumptions", "Used to demonstrate risk constraints and option scoring; this is not a portfolio backtest, capital model, or real underwriting outcome"), uncertainty: controlledUncertainty("finance-underwriting-v1"), constraints: [{ id: "capital", label: "Capital usage", metric: "cost", operator: "<=", value: 70 }, { id: "ops", label: "Manual-review capacity", metric: "capacity", operator: "<=", value: 50 }], options: [{ id: "pause", label: "Pause new admissions", benefit: 25, cost: 12, risk: 5, capacity: 8 }, { id: "tighten", label: "Tighten and manually review", benefit: 62, cost: 44, risk: 14, capacity: 48 }, { id: "expand", label: "Expand under the original policy", benefit: 98, cost: 65, risk: 34, capacity: 38 }] }],
};

export default FINANCIAL_RISK_CASE;
