import type { ExecutableCaseDefinition } from "../types";
import { confirmedThreshold, controlledUncertainty, manualDecisionInputs, syntheticPriorDecision } from "../types";

export const SPATIAL_PLANNING_CASE: ExecutableCaseDefinition = {
  id: "spatial-planning", title: "Spatial Planning: Site Demand and Accessibility", projectName: "Synthetic Site-Selection Audit", primaryKey: "site_id",
  baselineFile: "/cases/spatial-planning/baseline.csv", currentFile: "/cases/spatial-planning/current.csv", expectedGeneratedAt: "2026-08-08T00:00:00.000Z",
  claims: [
    { id: "spatial-demand-rank", code: "SP-001", title: "East remains the candidate zone with the highest demand index", section: "Demand ranking", owner: "Planning owner", category: "Spatial ranking", formula: "argmax(zone, demand_index) = East", rule: { type: "rank", field: "demand_index", aggregation: "average", groupField: "zone", expectedGroup: "East", rank: "max", tiePolicy: "require_unique" } },
    { id: "spatial-travel-gate", code: "SP-002", title: "Average travel time to candidate sites does not exceed 20 minutes", section: "Accessibility", owner: "Accessibility owner", category: "Accessibility threshold", formula: "mean(travel_minutes) <= 20", rule: { type: "threshold", field: "travel_minutes", aggregation: "average", operator: "<=", threshold: 20, thresholdSpec: confirmedThreshold(20, "absolute", "Synthetic accessibility standard v1", "An average of 20 minutes is the accessibility ceiling for candidate sites") } },
    { id: "spatial-flood-gate", code: "SP-003", title: "No candidate site has a flood-risk score above 3", section: "Risk constraints", owner: "Resilience owner", category: "Risk threshold", formula: "max(flood_risk) <= 3", rule: { type: "threshold", field: "flood_risk", aggregation: "max", operator: "<=", threshold: 3, thresholdSpec: confirmedThreshold(3, "score", "Synthetic resilience standard v1", "Eliminate candidate sites with a score above 3") } },
  ],
  decisions: [{ id: "spatial-site-choice", title: "Should the East site plan remain the recommendation?", owner: "Planning committee", passActionId: "spatial:advance-east-plan", holdActionId: "spatial:cancel-and-rerank", actionIfPass: "Keep East as the preferred site and advance to detailed planning.", actionIfFail: "Cancel the original preference and rerank using demand, accessibility, and flood constraints.", conditions: [{ claimId: "spatial-demand-rank", allowedStatuses: ["SUPPORTED"] }, { claimId: "spatial-flood-gate", allowedStatuses: ["SUPPORTED"] }], priorSignedResult: syntheticPriorDecision({ decisionId: "spatial-site-choice", versionId: "spatial-v1", outcome: "PASS", activeActionId: "spatial:advance-east-plan", activeActionInstruction: "Keep East as the preferred site and advance to detailed planning.", recommendedOptionId: "east", feasibleOptionIds: ["east"], claimIds: ["spatial-demand-rank", "spatial-flood-gate"], signedAt: "2026-08-01T08:00:00.000Z", signedBy: "Synthetic planning committee" }), stakeholders: ["Residents", "Planning department", "Emergency management"], objective: { benefitWeight: 1, costWeight: 0.2, riskWeight: 1.4 }, riskTolerance: 18, noActionLoss: 32, inputProvenance: manualDecisionInputs("Synthetic planning committee assumptions", "Used to demonstrate site-selection constraint scoring; this is not GIS accessibility, spatial-boundary, or real construction-cost analysis"), uncertainty: controlledUncertainty("spatial-site-v1"), constraints: [{ id: "capital", label: "Construction cost", metric: "cost", operator: "<=", value: 75 }, { id: "delivery", label: "Construction capacity", metric: "capacity", operator: "<=", value: 65 }], options: [{ id: "east", label: "Original East plan", benefit: 75, cost: 58, risk: 22, capacity: 54 }, { id: "west", label: "Revised West plan", benefit: 91, cost: 66, risk: 15, capacity: 62 }, { id: "dual", label: "Dual-site plan", benefit: 120, cost: 104, risk: 12, capacity: 96 }] }],
};

export default SPATIAL_PLANNING_CASE;
