import type { ExecutableCaseDefinition } from "../types";
import { confirmedThreshold, controlledUncertainty, manualDecisionInputs, syntheticPriorDecision } from "../types";

export const PUBLIC_POLICY_CASE: ExecutableCaseDefinition = {
  id: "public-policy", title: "Public Policy: Program Coverage and Outcome Thresholds", projectName: "Synthetic Public-Program Scale-Up Audit", primaryKey: "district_id",
  baselineFile: "/cases/public-policy/baseline.csv", currentFile: "/cases/public-policy/current.csv", expectedGeneratedAt: "2026-08-08T00:00:00.000Z",
  claims: [
    { id: "policy-coverage-stability", code: "PP-001", title: "Average district coverage remains stable after the version revision", section: "Program coverage", owner: "Program owner", category: "Coverage stability", formula: "relative_change(mean(coverage_percent)) <= 3%", rule: { type: "stability", field: "coverage_percent", aggregation: "average", supportTolerance: 3, reversalThreshold: 8, supportToleranceSpec: confirmedThreshold(3, "percent", "Synthetic program protocol v1", "Do not change the coverage judgment within a 3% shift"), reversalThresholdSpec: confirmedThreshold(8, "percent", "Synthetic policy escalation rule v1", "An 8% change reverses the coverage judgment") } },
    { id: "policy-outcome-gate", code: "PP-002", title: "The average outcome score reaches 72", section: "Outcome evaluation", owner: "Evaluation owner", category: "Outcome threshold", formula: "mean(outcome_score) >= 72", rule: { type: "threshold", field: "outcome_score", aggregation: "average", operator: ">=", threshold: 72, thresholdSpec: confirmedThreshold(72, "score", "Synthetic evaluation plan v1", "A score of 72 is the minimum outcome threshold before scale-up") } },
    { id: "policy-population-stability", code: "PP-003", title: "Average eligible-population size changes by no more than 5%", section: "Target population", owner: "Policy analyst", category: "Population stability", formula: "relative_change(mean(eligible_population)) <= 5%", rule: { type: "stability", field: "eligible_population", aggregation: "average", supportTolerance: 5, reversalThreshold: 15, supportToleranceSpec: confirmedThreshold(5, "percent", "Synthetic targeting plan v1", "Retain target-population assumptions within a 5% change"), reversalThresholdSpec: confirmedThreshold(15, "percent", "Synthetic targeting risk rule v1", "A 15% change invalidates the original target-population assumption") } },
  ],
  decisions: [{ id: "policy-scale", title: "Should program coverage expand under the original plan?", owner: "Program board", passActionId: "policy:continue-phased-scale", holdActionId: "policy:pause-and-redesign", actionIfPass: "Retain the phased scale-up plan.", actionIfFail: "Pause scale-up and redefine the cohort and cost-benefit assumptions.", conditions: [{ claimId: "policy-coverage-stability", allowedStatuses: ["SUPPORTED", "WEAKENED"] }, { claimId: "policy-outcome-gate", allowedStatuses: ["SUPPORTED"] }], priorSignedResult: syntheticPriorDecision({ decisionId: "policy-scale", versionId: "policy-v1", outcome: "PASS", activeActionId: "policy:continue-phased-scale", activeActionInstruction: "Retain the phased scale-up plan.", recommendedOptionId: "phased", feasibleOptionIds: ["no-scale", "phased"], claimIds: ["policy-coverage-stability", "policy-outcome-gate"], signedAt: "2026-08-01T08:00:00.000Z", signedBy: "Synthetic program board" }), stakeholders: ["Target population", "District implementers", "Finance department"], objective: { benefitWeight: 1, costWeight: 0.25, riskWeight: 1 }, riskTolerance: 22, noActionLoss: 40, inputProvenance: manualDecisionInputs("Synthetic program board assumptions", "Used to demonstrate cost, risk, and capacity constraints; these are not causal effects, real fiscal costs, or policy-benefit estimates"), uncertainty: controlledUncertainty("policy-scale-v1"), constraints: [{ id: "budget", label: "Fiscal budget", metric: "cost", operator: "<=", value: 65 }, { id: "delivery", label: "Delivery capacity", metric: "capacity", operator: "<=", value: 55 }], options: [{ id: "no-scale", label: "Do not scale yet", benefit: 24, cost: 8, risk: 6, capacity: 5 }, { id: "phased", label: "Phased scale-up", benefit: 78, cost: 52, risk: 18, capacity: 48 }, { id: "full-scale", label: "Immediate full scale-up", benefit: 112, cost: 88, risk: 32, capacity: 80 }] }],
};

export default PUBLIC_POLICY_CASE;
