import type { ExecutableCaseDefinition } from "../types";
import { confirmedThreshold, controlledUncertainty, filter, manualDecisionInputs, syntheticPriorDecision } from "../types";

export const POPULATION_HEALTH_CASE: ExecutableCaseDefinition = {
  id: "population-health", title: "Population Health: Follow-Up Priorities and Model Gating", projectName: "Synthetic Population-Health Evidence Audit", primaryKey: "row_id",
  baselineFile: "/cases/population-health/baseline.csv", currentFile: "/cases/population-health/current.csv", upstreamLineageFile: "/cases/population-health/upstream-lineage.json", expectedGeneratedAt: "2026-08-08T00:00:00.000Z",
  claims: [
    { id: "north-risk", code: "CT-001", title: "North has the highest high-risk rate among the four regions and should receive follow-up resources first", section: "Executive summary · paragraph 2", owner: "ClaimTrace demonstration", category: "Resource allocation", formula: "argmax(segment, value) where indicator = High-risk rate", rule: { type: "rank", field: "value", aggregation: "average", groupField: "segment", expectedGroup: "North", rank: "max", filters: [filter("indicator", "High-risk rate")] } },
    { id: "recall-gate", code: "CT-002", title: "Model recall exceeds the 80% deployment gate, allowing a controlled pilot", section: "Model evaluation · paragraph 4", owner: "ClaimTrace demonstration", category: "Model gate", formula: "TP / (TP + FN) > 80%", rule: { type: "threshold", field: "value", aggregation: "average", operator: ">", threshold: 80, filters: [filter("indicator", "Model recall"), filter("segment", "Citywide")], thresholdSpec: confirmedThreshold(80, "percent", "Synthetic model admission policy v1", "Do not begin the pilot when recall is below 80%") } },
    { id: "followup-gap", code: "CT-003", title: "Citywide follow-up completion is below the 80% target, requiring additional outreach capacity", section: "Operations diagnosis · paragraph 1", owner: "ClaimTrace demonstration", category: "Operations diagnosis", formula: "completed / eligible < 80%", rule: { type: "threshold", field: "value", aggregation: "average", operator: "<", threshold: 80, filters: [filter("indicator", "Follow-up completion rate"), filter("segment", "Citywide")], thresholdSpec: confirmedThreshold(80, "percent", "Synthetic follow-up target policy v1", "The annual follow-up completion target is 80%") } },
    { id: "east-completion", code: "CT-004", title: "East retains the highest follow-up completion rate and can serve as a process-replication example", section: "Regional case · paragraph 3", owner: "ClaimTrace demonstration", category: "Best practice", formula: "argmax(segment, value) where indicator = Follow-up completion rate", rule: { type: "rank", field: "value", aggregation: "average", groupField: "segment", expectedGroup: "East", rank: "max", filters: [filter("indicator", "Follow-up completion rate")], excludes: [filter("segment", "Citywide")] } },
    { id: "west-risk", code: "CT-005", title: "West still has the lowest high-risk rate and should not be overprioritized because of total volume", section: "Resource allocation · paragraph 5", owner: "ClaimTrace demonstration", category: "Resource allocation", formula: "argmin(segment, value) where indicator = High-risk rate", rule: { type: "rank", field: "value", aggregation: "average", groupField: "segment", expectedGroup: "West", rank: "min", filters: [filter("indicator", "High-risk rate")] } },
  ],
  decisions: [
    { id: "decision-model-pilot", title: "Should the risk model enter a controlled pilot?", owner: "Model governance lead", passActionId: "health:model-controlled-pilot", holdActionId: "health:model-pause-and-remediate", actionIfPass: "Begin a controlled pilot and continue monitoring recall.", actionIfFail: "Pause the pilot, remediate false negatives, and validate again.", conditions: [{ claimId: "recall-gate", allowedStatuses: ["SUPPORTED"] }], priorSignedResult: syntheticPriorDecision({ decisionId: "decision-model-pilot", versionId: "health-v1", outcome: "PASS", activeActionId: "health:model-controlled-pilot", activeActionInstruction: "Begin a controlled pilot and continue monitoring recall.", recommendedOptionId: "full-pilot", feasibleOptionIds: ["hold", "limited-pilot", "full-pilot"], claimIds: ["recall-gate"], signedAt: "2026-07-31T10:00:00.000Z", signedBy: "Synthetic model owner" }), stakeholders: ["Model governance", "Follow-up team", "Patient safety"], objective: { benefitWeight: 1, costWeight: 0.15, riskWeight: 1.2 }, riskTolerance: 24, noActionLoss: 45, inputProvenance: manualDecisionInputs("Synthetic model governance assumptions", "Used to demonstrate model-pilot option scoring; these are not clinical utility, patient outcomes, or real operating-cost estimates"), uncertainty: controlledUncertainty("health-model-pilot-v1"), constraints: [{ id: "pilot-budget", label: "Pilot budget", metric: "cost", operator: "<=", value: 60 }, { id: "review-capacity", label: "Manual-review capacity", metric: "capacity", operator: "<=", value: 40 }], options: [{ id: "hold", label: "Pause and retrain", benefit: 45, cost: 32, risk: 8, capacity: 18 }, { id: "limited-pilot", label: "Limited controlled pilot", benefit: 82, cost: 54, risk: 22, capacity: 36 }, { id: "full-pilot", label: "Full pilot", benefit: 108, cost: 86, risk: 38, capacity: 62 }] },
    { id: "decision-followup-allocation", title: "Should North receive follow-up resources under the original plan?", owner: "Operations lead", passActionId: "health:keep-north-priority", holdActionId: "health:freeze-and-reallocate", actionIfPass: "The original resource priority remains supported.", actionIfFail: "Freeze the original ranking and reallocate resources using the revised version.", conditions: [{ claimId: "north-risk", allowedStatuses: ["SUPPORTED", "WEAKENED"] }], priorSignedResult: syntheticPriorDecision({ decisionId: "decision-followup-allocation", versionId: "health-v1", outcome: "PASS", activeActionId: "health:keep-north-priority", activeActionInstruction: "The original resource priority remains supported.", recommendedOptionId: "keep", feasibleOptionIds: ["keep"], claimIds: ["north-risk"], signedAt: "2026-07-31T10:05:00.000Z", signedBy: "Synthetic operations owner" }), stakeholders: ["North team", "Other regions", "Operations management"], objective: { benefitWeight: 1, costWeight: 0.2, riskWeight: 0.8 }, riskTolerance: 20, noActionLoss: 30, inputProvenance: manualDecisionInputs("Synthetic follow-up operations assumptions", "Used to demonstrate resource-allocation scoring; these are not observed health benefits, real follow-up costs, or real capacity"), uncertainty: controlledUncertainty("health-followup-allocation-v1"), constraints: [{ id: "visit-capacity", label: "Additional follow-up capacity", metric: "capacity", operator: "<=", value: 50 }], options: [{ id: "keep", label: "Keep the original allocation", benefit: 48, cost: 18, risk: 19, capacity: 12 }, { id: "rebalance", label: "Reallocate by revised ranking", benefit: 76, cost: 28, risk: 12, capacity: 42 }, { id: "expand-all", label: "Expand capacity across all regions", benefit: 92, cost: 64, risk: 9, capacity: 78 }] },
  ],
};

export default POPULATION_HEALTH_CASE;
