import type { CaseDefinition } from "../core";
import { BUSINESS_OPERATIONS_CASE } from "./business-operations/case";
import { FINANCIAL_RISK_CASE } from "./financial-risk/case";
import { POPULATION_HEALTH_CASE } from "./population-health/case";
import { SPATIAL_PLANNING_CASE } from "./spatial-planning/case";
import { WORLD_BANK_LIFE_EXPECTANCY_CASE } from "./world-bank-life-expectancy/case";
import { USDOT_TRANSIT_OPERATIONS_CASE } from "./usdot-transit-operations/case";
import { US_TREASURY_YIELD_CURVE_CASE } from "./us-treasury-yield-curve/case";
import { CFPB_CREDIT_CARD_COMPLAINTS_CASE } from "./cfpb-credit-card-complaints/case";
import { CDC_PLACES_DEPRESSION_CASE } from "./cdc-places-depression/case";
import { ONS_HOUSING_AFFORDABILITY_CASE } from "./ons-housing-affordability/case";

export * from "./types";
export * from "./runtime";
export * from "./business-operations/case";
export * from "./financial-risk/case";
export * from "./population-health/case";
export * from "./spatial-planning/case";
export * from "./world-bank-life-expectancy/case";
export * from "./usdot-transit-operations/case";
export * from "./us-treasury-yield-curve/case";
export * from "./cfpb-credit-card-complaints/case";
export * from "./cdc-places-depression/case";
export * from "./ons-housing-affordability/case";

export const EXECUTABLE_CASES = [
  BUSINESS_OPERATIONS_CASE,
  FINANCIAL_RISK_CASE,
  POPULATION_HEALTH_CASE,
  SPATIAL_PLANNING_CASE,
  WORLD_BANK_LIFE_EXPECTANCY_CASE,
  USDOT_TRANSIT_OPERATIONS_CASE,
  US_TREASURY_YIELD_CURVE_CASE,
  CFPB_CREDIT_CARD_COMPLAINTS_CASE,
  CDC_PLACES_DEPRESSION_CASE,
  ONS_HOUSING_AFFORDABILITY_CASE,
];

export const CASE_CATALOG: CaseDefinition[] = [
  {
    id: "business-operations",
    domain: "business",
    title: "Business Operations: Channel Conversion and Service Capacity",
    question: "Should media spend and service capacity be reallocated after channel rankings change?",
    primaryKey: "channel_id",
    baselineFile: "/cases/business-operations/baseline.csv",
    currentFile: "/cases/business-operations/current.csv",
    claimCount: 3,
    decisionCount: 1,
    synthetic: true,
    method: "Grouped rank, threshold, and stability rules",
    capabilities: ["business analytics", "operations", "capacity decisions", "communication"],
    boundary: "Controlled regression fixture; no client, spend, revenue, or measured operating impact.",
    dataCard: "docs/data-cards/business-operations.md",
    claimsFile: "/cases/business-operations/claims.json",
    decisionsFile: "/cases/business-operations/decisions.json",
    expectedAuditFile: "/cases/business-operations/expected-audit.json",
    readmeFile: "/cases/business-operations/README.md",
  },
  {
    id: "financial-risk",
    domain: "finance",
    title: "Financial Risk: Portfolio Risk and Admission Thresholds",
    question: "Can the original admission policy still be used after default probabilities and valid samples change?",
    primaryKey: "account_id",
    baselineFile: "/cases/financial-risk/baseline.csv",
    currentFile: "/cases/financial-risk/current.csv",
    claimCount: 3,
    decisionCount: 1,
    synthetic: true,
    method: "Portfolio means, membership changes, missingness, and governed risk thresholds",
    capabilities: ["financial risk", "model monitoring", "threshold governance", "decision analysis"],
    boundary: "Synthetic credit records; not a calibrated risk model, underwriting policy, or backtest.",
    dataCard: "docs/data-cards/financial-risk.md",
    claimsFile: "/cases/financial-risk/claims.json",
    decisionsFile: "/cases/financial-risk/decisions.json",
    expectedAuditFile: "/cases/financial-risk/expected-audit.json",
    readmeFile: "/cases/financial-risk/README.md",
  },
  {
    id: "population-health",
    domain: "health",
    title: "Population Health: Follow-Up Priorities and Model Gating",
    question: "Do revised risk and recall rates change the pilot decision or resource priorities?",
    primaryKey: "row_id",
    baselineFile: "/cases/population-health/baseline.csv",
    currentFile: "/cases/population-health/current.csv",
    claimCount: 5,
    decisionCount: 2,
    synthetic: true,
    method: "Raw-to-summary lineage, recall gating, regional ranks, and constrained options",
    capabilities: ["AI governance", "health analytics", "data lineage", "resource allocation"],
    boundary: "Synthetic model and follow-up records; no clinical validation, patient outcome, or deployment.",
    dataCard: "docs/data-cards/population-health.md",
    claimsFile: "/cases/population-health/claims.json",
    decisionsFile: "/cases/population-health/decisions.json",
    expectedAuditFile: "/cases/population-health/expected-audit.json",
    readmeFile: "/cases/population-health/README.md",
  },
  {
    id: "spatial-planning",
    domain: "spatial",
    title: "Spatial Planning: Site Demand and Accessibility",
    question: "Should the candidate site change after demand-center and accessibility rankings shift?",
    primaryKey: "site_id",
    baselineFile: "/cases/spatial-planning/baseline.csv",
    currentFile: "/cases/spatial-planning/current.csv",
    claimCount: 3,
    decisionCount: 1,
    synthetic: true,
    method: "Demand and accessibility ranks with risk and capacity constraints",
    capabilities: ["spatial planning", "multi-criteria decisions", "accessibility", "sensitivity"],
    boundary: "Synthetic attribute-table fixture; no GIS network, fieldwork, or regeneration impact estimate.",
    dataCard: "docs/data-cards/spatial-planning.md",
    claimsFile: "/cases/spatial-planning/claims.json",
    decisionsFile: "/cases/spatial-planning/decisions.json",
    expectedAuditFile: "/cases/spatial-planning/expected-audit.json",
    readmeFile: "/cases/spatial-planning/README.md",
  },
  {
    id: "world-bank-life-expectancy",
    domain: "public-data",
    title: "Public Data: World Bank Life-Expectancy Cross-Year Audit",
    question: "Which descriptive claims and publication notes must change after the 2019 and 2024 indicator snapshots are compared?",
    primaryKey: "country_code",
    baselineFile: "/cases/world-bank-life-expectancy/baseline.csv",
    currentFile: "/cases/world-bank-life-expectancy/current.csv",
    claimCount: 3,
    decisionCount: 1,
    synthetic: false,
    method: "Cross-year ranks, descriptive thresholds, and selected-country mean stability",
    capabilities: ["population indicators", "public-data provenance", "cross-country comparison", "reproducibility"],
    boundary: "Selected descriptive indicators; not a causal, representative, or country-performance study.",
    sourceMetadataFile: "/cases/world-bank-life-expectancy/source-metadata.json",
    dataCard: "/cases/world-bank-life-expectancy/README.md",
    claimsFile: "/cases/world-bank-life-expectancy/claims.json",
    decisionsFile: "/cases/world-bank-life-expectancy/decisions.json",
    expectedAuditFile: "/cases/world-bank-life-expectancy/expected-audit.json",
    readmeFile: "/cases/world-bank-life-expectancy/README.md",
  },
  {
    id: "usdot-transit-operations",
    domain: "business",
    title: "Public Data: USDOT Transit Operations Period Audit",
    question: "Can a prior heavy-rail operating brief be reused after ridership and service intensity change?",
    primaryKey: "ntd_id",
    baselineFile: "/cases/usdot-transit-operations/baseline.csv",
    currentFile: "/cases/usdot-transit-operations/current.csv",
    claimCount: 3,
    decisionCount: 1,
    synthetic: false,
    method: "Ridership-per-hour derivation, threshold review, and period stability",
    capabilities: ["operations analytics", "public infrastructure", "source adapters", "human review"],
    boundary: "Selected public transit rows; not causal efficiency, service quality, or client work.",
    sourceMetadataFile: "/cases/usdot-transit-operations/source-metadata.json",
    dataCard: "/cases/usdot-transit-operations/README.md",
    claimsFile: "/cases/usdot-transit-operations/claims.json",
    decisionsFile: "/cases/usdot-transit-operations/decisions.json",
    expectedAuditFile: "/cases/usdot-transit-operations/expected-audit.json",
    readmeFile: "/cases/usdot-transit-operations/README.md",
  },
  {
    id: "us-treasury-yield-curve",
    domain: "finance",
    title: "Public Data: U.S. Treasury Yield-Curve Period Audit",
    question: "Which curve-shape and short-end claims change between the two year-end snapshots?",
    primaryKey: "maturity_code",
    baselineFile: "/cases/us-treasury-yield-curve/baseline.csv",
    currentFile: "/cases/us-treasury-yield-curve/current.csv",
    claimCount: 3,
    decisionCount: 1,
    synthetic: false,
    method: "Curve-shape ranks, short-end threshold, and period-mean stability",
    capabilities: ["fixed income", "risk communication", "financial data provenance", "decision discipline"],
    boundary: "Descriptive Treasury observations; not trading, valuation, allocation, or return evidence.",
    sourceMetadataFile: "/cases/us-treasury-yield-curve/source-metadata.json",
    dataCard: "/cases/us-treasury-yield-curve/README.md",
    claimsFile: "/cases/us-treasury-yield-curve/claims.json",
    decisionsFile: "/cases/us-treasury-yield-curve/decisions.json",
    expectedAuditFile: "/cases/us-treasury-yield-curve/expected-audit.json",
    readmeFile: "/cases/us-treasury-yield-curve/README.md",
  },
  {
    id: "cfpb-credit-card-complaints",
    domain: "finance",
    title: "Public Data: CFPB Credit-Card Complaint Pattern Audit",
    question: "Do structured issue rankings, shares, or record volume require the prior consumer-friction brief to change?",
    primaryKey: "issue_id",
    baselineFile: "/cases/cfpb-credit-card-complaints/baseline.csv",
    currentFile: "/cases/cfpb-credit-card-complaints/current.csv",
    claimCount: 3,
    decisionCount: 1,
    synthetic: false,
    method: "Issue ranks, matched shares, denominator tracking, and volume stability",
    capabilities: ["consumer finance", "behavioral context", "sampling limits", "policy communication"],
    boundary: "Complaint patterns are not representative incidence, adjudicated findings, or intervention effects.",
    sourceMetadataFile: "/cases/cfpb-credit-card-complaints/source-metadata.json",
    dataCard: "/cases/cfpb-credit-card-complaints/README.md",
    claimsFile: "/cases/cfpb-credit-card-complaints/claims.json",
    decisionsFile: "/cases/cfpb-credit-card-complaints/decisions.json",
    expectedAuditFile: "/cases/cfpb-credit-card-complaints/expected-audit.json",
    readmeFile: "/cases/cfpb-credit-card-complaints/README.md",
  },
  {
    id: "cdc-places-depression",
    domain: "health",
    title: "Public Data: CDC PLACES Model-Based Estimate Audit",
    question: "Which selected-county descriptive statements need revision when the model-based estimates update?",
    primaryKey: "county_fips",
    baselineFile: "/cases/cdc-places-depression/baseline.csv",
    currentFile: "/cases/cdc-places-depression/current.csv",
    claimCount: 4,
    decisionCount: 1,
    synthetic: false,
    method: "Point-estimate ranks, thresholds, interval-aware gates, and period stability",
    capabilities: ["health data", "statistical uncertainty", "surveillance", "methods review"],
    boundary: "Model-based county estimates; not diagnosis, epidemiology, causal intervention, or clinical advice.",
    sourceMetadataFile: "/cases/cdc-places-depression/source-metadata.json",
    dataCard: "/cases/cdc-places-depression/README.md",
    claimsFile: "/cases/cdc-places-depression/claims.json",
    decisionsFile: "/cases/cdc-places-depression/decisions.json",
    expectedAuditFile: "/cases/cdc-places-depression/expected-audit.json",
    readmeFile: "/cases/cdc-places-depression/README.md",
  },
  {
    id: "ons-housing-affordability",
    domain: "spatial",
    title: "Public Data: ONS Housing-Affordability Period Audit",
    question: "Can the selected-authority planning context note be reused after affordability ratios change?",
    primaryKey: "authority_code",
    baselineFile: "/cases/ons-housing-affordability/baseline.csv",
    currentFile: "/cases/ons-housing-affordability/current.csv",
    claimCount: 3,
    decisionCount: 1,
    synthetic: false,
    method: "Selected-authority ranks, affordability thresholds, and period stability",
    capabilities: ["planning evidence", "housing affordability", "official statistics", "place-based decisions"],
    boundary: "Attribute-table context only; no GIS geometry, spatial econometrics, fieldwork, or impact evaluation.",
    sourceMetadataFile: "/cases/ons-housing-affordability/source-metadata.json",
    dataCard: "/cases/ons-housing-affordability/README.md",
    claimsFile: "/cases/ons-housing-affordability/claims.json",
    decisionsFile: "/cases/ons-housing-affordability/decisions.json",
    expectedAuditFile: "/cases/ons-housing-affordability/expected-audit.json",
    readmeFile: "/cases/ons-housing-affordability/README.md",
  },
];
