import type { ExecutableCaseDefinition } from "../types";
import { controlledUncertainty, filter, publicConfirmedThreshold, publicManualDecisionInputs } from "../types";

export const CDC_PLACES_DEPRESSION_CASE: ExecutableCaseDefinition = {
  id: "cdc-places-depression",
  title: "Public Data: CDC PLACES Model-Based Estimate Audit",
  projectName: "CDC PLACES Selected-County Depression Estimate Audit",
  primaryKey: "county_fips",
  baselineFile: "/cases/cdc-places-depression/baseline.csv",
  currentFile: "/cases/cdc-places-depression/current.csv",
  sourceMetadataFile: "/cases/cdc-places-depression/source-metadata.json",
  dataOrigin: "PUBLIC",
  expectedGeneratedAt: "2026-08-10T00:00:00.000Z",
  claims: [
    {
      id: "places-middlesex-rank",
      code: "CDC-001",
      title: "Middlesex County remains the highest point estimate among the eight selected counties",
      section: "Model-based estimate ranking",
      owner: "Public-data case reviewer",
      category: "County ranking",
      formula: "argmax(county, age_adjusted_depression_percent) = Middlesex",
      rule: { type: "rank", field: "age_adjusted_depression_percent", aggregation: "average", groupField: "county", expectedGroup: "Middlesex", rank: "max", tiePolicy: "require_unique" },
    },
    {
      id: "places-maricopa-threshold",
      code: "CDC-002",
      title: "Maricopa County's age-adjusted model-based estimate remains at or above 20%",
      section: "Illustrative estimate threshold",
      owner: "Public-data case reviewer",
      category: "Threshold gate",
      formula: "Maricopa age_adjusted_depression_percent >= 20",
      rule: { type: "threshold", field: "age_adjusted_depression_percent", aggregation: "average", operator: ">=", threshold: 20, filters: [filter("county_fips", "04013")], thresholdSpec: publicConfirmedThreshold(20, "percent", "Illustrative surveillance review threshold v1", "An analyst-authored threshold for claim auditing; it is not CDC guidance, a diagnosis threshold, or an intervention rule") },
    },
    {
      id: "places-selected-mean-stability",
      code: "CDC-003",
      title: "The unweighted mean point estimate across the eight selected counties changes by no more than 2%",
      section: "Selected-county descriptive stability",
      owner: "Public-data case reviewer",
      category: "Period stability",
      formula: "abs(mean(2023 estimates)-mean(2022 estimates))/mean(2022 estimates) <= 2%",
      rule: { type: "stability", field: "age_adjusted_depression_percent", aggregation: "average", supportTolerance: 2, reversalThreshold: 5, supportToleranceSpec: publicConfirmedThreshold(2, "percent", "Illustrative surveillance-summary rule v1", "Used to audit a compact descriptive statement; confidence intervals remain visible and must be interpreted separately"), reversalThresholdSpec: publicConfirmedThreshold(5, "percent", "Illustrative surveillance-summary escalation v1", "At 5%, treat the compact selected-county mean statement as materially invalid") },
    },
    {
      id: "places-maricopa-interval",
      code: "CDC-004",
      title: "Maricopa County's complete 95% confidence interval remains at or above 18%",
      section: "Interval-aware estimate gate",
      owner: "Public-data case reviewer",
      category: "Uncertainty-aware threshold",
      formula: "Maricopa ci_low_percent >= 18 with point estimate and 95% confidence interval retained",
      rule: { type: "interval-threshold", field: "age_adjusted_depression_percent", lowerField: "ci_low_percent", upperField: "ci_high_percent", aggregation: "average", operator: ">=", threshold: 18, intervalLevel: 0.95, intervalLabel: "95% confidence interval", filters: [filter("county_fips", "04013")], thresholdSpec: publicConfirmedThreshold(18, "percent", "Illustrative uncertainty-review threshold v1", "Tests whether the complete reported interval, rather than only the point estimate, clears an analyst-authored descriptive threshold; this is not CDC guidance or a clinical rule") },
    },
  ],
  decisions: [{
    id: "places-surveillance-note",
    title: "Can the earlier selected-county surveillance note be reused without revision?",
    owner: "Public-data case reviewer",
    passActionId: "places:retain-note-with-model-warning",
    holdActionId: "places:update-estimates-and-uncertainty",
    actionIfPass: "Retain only supported descriptive statements and show model-based-estimate, confidence-interval, year, and selection limitations.",
    actionIfFail: "Update changed point-estimate statements and preserve confidence intervals; do not infer local program effects or individual risk.",
    conditions: [{ claimId: "places-middlesex-rank", allowedStatuses: ["SUPPORTED"] }, { claimId: "places-maricopa-threshold", allowedStatuses: ["SUPPORTED"] }, { claimId: "places-selected-mean-stability", allowedStatuses: ["SUPPORTED", "WEAKENED"] }, { claimId: "places-maricopa-interval", allowedStatuses: ["SUPPORTED"] }],
    stakeholders: ["Population-health readers", "Methods reviewers", "Public-data provider"],
    objective: { benefitWeight: 1, costWeight: 0.2, riskWeight: 1.3 },
    riskTolerance: 16,
    noActionLoss: 32,
    inputProvenance: publicManualDecisionInputs("Illustrative health-publication assumptions v1", "The option scores are demonstration inputs, not clinical utility, disease burden, intervention effects, or real operating costs"),
    uncertainty: controlledUncertainty("places-surveillance-note-v1"),
    constraints: [{ id: "methods-capacity", label: "Methods-review capacity", metric: "capacity", operator: "<=", value: 45 }],
    options: [
      { id: "reuse", label: "Reuse unchanged", benefit: 30, cost: 6, risk: 34, capacity: 4 },
      { id: "revise", label: "Revise estimates and uncertainty notes", benefit: 85, cost: 27, risk: 7, capacity: 27 },
      { id: "survey", label: "Commission direct local measurement", benefit: 110, cost: 96, risk: 10, capacity: 90 },
    ],
  }],
};

export default CDC_PLACES_DEPRESSION_CASE;
